### ISSUE TITLE
Delegate keeps crashing

### ISSUE THREAD

**Issue by josefantoni** [luisfcofv/LFSideViewController#3]
I am using your tool, and  
self.sideViewController()!.delegate = self
keeps crashing. so i ignore it but now i have 3 view and they are on top of each other and they not unloading. Can u please help?

I have a huge memory leaks .....have 3 map views with X 0000 PINs

**Comment by josefantoni** [comment]
I see that delegate handling UNLOADING stuff.

**Comment by luisfcofv** [comment]
I will try to fix it today and add a better example. 
Feel free to do pull request as well. Thanks
